/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{js,jsx}", "./components/**/*.{js,jsx}", "./app/**/*.{js,jsx}", "./src/**/*.{js,jsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 20px hsl(40 70% 50% / 0.15)" },
          "50%": { boxShadow: "0 0 30px hsl(40 70% 50% / 0.3)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
        "pulse-glow": "pulse-glow 3s ease-in-out infinite",
      },
    },
  },
  safelist: [
    // Safelist dynamic classes that might be purged
    {
      pattern: /^(bg-(?:slate|gray|zinc|neutral|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern: /^(text-(?:slate|gray|zinc|neutral|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern: /^(border-(?:slate|gray|zinc|neutral|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    // Safelist opacity variations used in the project
    {
      pattern: /(bg|text|border|divide|ring)-.*\/(5|10|20|25|30|40|50|60|70|75|80|90|95)/,
    },
    // Safelist specific custom classes used in the project
    'bg-primary/5',
    'bg-success/5',
    'bg-destructive/5',
    'bg-warning/5',
    'bg-success/10',
    'bg-warning/10',
    'bg-destructive/70',
    'bg-primary/10',
    'bg-primary/20',
    'bg-primary/90',
    'bg-secondary/80',
    'bg-accent',
    'bg-accent/80',
    'bg-muted/80',
    'bg-popover',
    'bg-popover/90',
    'bg-card',
    'bg-card/80',
    'bg-background',
    'bg-foreground/30',
    'bg-white/10',
    'bg-black/10',
    'bg-black/20',
    'bg-white/20',
    'bg-primary-foreground/10',
    'bg-primary-foreground/15',
    'bg-primary-foreground/20',
    'bg-primary-foreground/25',
    'bg-primary-foreground/30',
    'bg-primary-foreground/40',
    'bg-primary-foreground/50',
    'bg-primary-foreground/60',
    'bg-primary-foreground/70',
    'bg-primary-foreground/80',
    'bg-primary-foreground/90',
    'bg-primary-foreground/95',
    'bg-muted-foreground/10',
    'bg-muted-foreground/20',
    'bg-muted-foreground/30',
    'bg-muted-foreground/40',
    'bg-muted-foreground/50',
    'bg-muted-foreground/60',
    'bg-muted-foreground/70',
    'bg-muted-foreground/80',
    'bg-muted-foreground/90',
    'bg-muted-foreground/95',
    'bg-sidebar-background',
    'bg-sidebar-foreground',
    'bg-sidebar-primary',
    'bg-sidebar-primary-foreground',
    'bg-sidebar-accent',
    'bg-sidebar-accent-foreground',
    'bg-sidebar-border',
    'bg-sidebar-ring',
    'text-primary-foreground/5',
    'text-primary-foreground/10',
    'text-primary-foreground/20',
    'text-primary-foreground/25',
    'text-primary-foreground/30',
    'text-primary-foreground/40',
    'text-primary-foreground/50',
    'text-primary-foreground/60',
    'text-primary-foreground/70',
    'text-primary-foreground/75',
    'text-primary-foreground/80',
    'text-primary-foreground/90',
    'text-primary-foreground/95',
    'text-muted-foreground/5',
    'text-muted-foreground/10',
    'text-muted-foreground/20',
    'text-muted-foreground/25',
    'text-muted-foreground/30',
    'text-muted-foreground/40',
    'text-muted-foreground/50',
    'text-muted-foreground/60',
    'text-muted-foreground/70',
    'text-muted-foreground/75',
    'text-muted-foreground/80',
    'text-muted-foreground/90',
    'text-muted-foreground/95',
    'border-primary-foreground/5',
    'border-primary-foreground/10',
    'border-primary-foreground/20',
    'border-primary-foreground/25',
    'border-primary-foreground/30',
    'border-primary-foreground/40',
    'border-primary-foreground/50',
    'border-primary-foreground/60',
    'border-primary-foreground/70',
    'border-primary-foreground/75',
    'border-primary-foreground/80',
    'border-primary-foreground/90',
    'border-primary-foreground/95',
    'border-muted-foreground/5',
    'border-muted-foreground/10',
    'border-muted-foreground/20',
    'border-muted-foreground/25',
    'border-muted-foreground/30',
    'border-muted-foreground/40',
    'border-muted-foreground/50',
    'border-muted-foreground/60',
    'border-muted-foreground/70',
    'border-muted-foreground/75',
    'border-muted-foreground/80',
    'border-muted-foreground/90',
    'border-muted-foreground/95',
  ],
  plugins: [require("tailwindcss-animate")],
};